package cn.c1clip.receiver;
import org.junit.Test;
import static org.junit.Assert.*;
public class FillSessionTest {
    @Test public void saveAttemptsAreStrictlyBounded(){assertEquals(3,FillSession.MAX_ATTEMPTS);}
    @Test public void clicksDoNotCountAsSaved(){FillSession s=new FillSession(0,false);s.submitted(1000);assertEquals(0,s.index);assertFalse(s.maySubmit(50000));s.saved();assertEquals(1,s.index);assertTrue(s.maySubmit(50000));}
    @Test public void retriesRequireExplicitFailureAndContinueAfterRecovery(){FillSession s=new FillSession(0,false);for(int i=0;i<6;i++){long now=(i+1)*2000;assertTrue(s.maySubmit(now));s.submitted(now);assertFalse(s.maySubmit(now+1500));s.failedExplicitly();assertFalse(s.maySubmit(now+100));}assertTrue(s.maySubmit(50000));assertEquals(0,s.index);}
    @Test public void uncertainSubmissionSurvivesResume(){FillSession s=new FillSession(2,true);assertFalse(s.maySubmit(999999));assertEquals(2,s.index);s.saved();assertEquals(3,s.index);assertTrue(s.maySubmit(999999));}
    @Test public void verificationBackIsPersistableAndClearedOnlyByOutcome(){FillSession s=new FillSession(1,false);s.submitted(100);s.startedVerification();assertTrue(s.verificationStarted);FillSession resumed=new FillSession(s.index,s.pending,s.verificationStarted);assertTrue(resumed.verificationStarted);resumed.failedExplicitly();assertFalse(resumed.verificationStarted);}
    @Test public void validatesMaskedIdentityInsteadOfTrustingNavigation(){assertTrue(FillSession.maskedIdMatches("身份证 000***********001","000000200001010001"));assertFalse(FillSession.maskedIdMatches("身份证 001***********002","000000200001010001"));assertFalse(FillSession.maskedIdMatches("添加成功","000000200001010001"));}
    @Test public void validatesMaoyanNamesWithPrivacyPrefix(){assertTrue(FillSession.maskedNameMatches("*张蕊","张蕊"));assertTrue(FillSession.maskedNameMatches("**蕊","张蕊"));assertTrue(FillSession.maskedNameMatches("张蕊","张蕊"));assertFalse(FillSession.maskedNameMatches("*梦帆","张蕊"));}
    @Test public void validationAndRateLimitsAreNeverRetried(){assertTrue(FillSession.permanentError("证件号码错误"));assertTrue(FillSession.permanentError("操作频繁，请稍后重试"));assertFalse(FillSession.transientError("操作频繁，请稍后重试"));assertTrue(FillSession.transientError("添加观演人信息失败"));assertFalse(FillSession.transientError("请输入姓名"));}
    @Test public void peopleAdvanceIndependently(){FillSession s=new FillSession(0,false);for(int i=0;i<3;i++){s.submitted(i*2000);assertEquals(i,s.index);s.saved();assertEquals(i+1,s.index);assertEquals(0,s.attempts);}}
    @Test public void postSaveListSyncWaitIsBounded(){assertTrue(FillSession.shouldWaitForListSync(true,1000,3999));assertFalse(FillSession.shouldWaitForListSync(true,1000,4000));assertFalse(FillSession.shouldWaitForListSync(false,1000,1200));assertFalse(FillSession.shouldWaitForListSync(true,0,1200));}
    @Test public void uncertainFormPausesWithoutMakingSubmissionRetryable(){FillSession s=new FillSession(0,false);s.submitted(1000);assertFalse(FillSession.shouldPauseUncertainForm(true,1000,12999));assertTrue(FillSession.shouldPauseUncertainForm(true,1000,13000));assertFalse(s.maySubmit(999999));assertTrue(s.pending);}
    @Test public void restoredPendingFormIsNeverClickedAgainBlindly(){FillSession s=new FillSession(1,true,true);assertTrue(FillSession.shouldPauseUncertainForm(s.pending,s.sentAt,500));assertFalse(s.maySubmit(500));assertEquals(1,s.index);}
}
